import React, { useState, useEffect } from 'react';
import { 
  X, 
  Sparkles, 
  AlertTriangle, 
  TrendingUp, 
  TrendingDown, 
  Clock, 
  ShieldCheck, 
  CheckCircle2, 
  Zap, 
  BarChart2 
} from 'lucide-react';
import { MacroEvent } from '../types';

interface MacroAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  event: MacroEvent | null;
  user?: { id?: string; email?: string } | null;
}

export const MacroAnalysisModal: React.FC<MacroAnalysisModalProps> = ({
  isOpen,
  onClose,
  event,
  user
}) => {
  const [analysisText, setAnalysisText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isOpen || !event) {
      setAnalysisText(null);
      return;
    }

    const fetchAnalysis = async () => {
      setLoading(true);
      try {
        // Map currency (USD, EUR, GBP, etc.) → primary pair to analyze
        const cur = String(event.currency || 'USD').toUpperCase();
        const pairMap: Record<string, string> = {
          USD: 'XAUUSD',    // USD events → analyze gold (most responsive)
          EUR: 'EURUSD',
          GBP: 'GBPUSD',
          JPY: 'USDJPY',
          CHF: 'USDCHF',
          CAD: 'USDCAD',
          AUD: 'AUDUSD',
          NZD: 'NZDUSD',
          CNY: 'XAUUSD',    // CNY events impact gold
        };
        const primaryPair = pairMap[cur] || 'XAUUSD';

        // Fetch live engine analysis + news bias in parallel
        const [engineRes, newsRes] = await Promise.all([
          fetch('/api/engine/analyze', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ symbol: primaryPair, timeframe: 'M15', userId: user?.id })
          }).then(r => r.json()).catch(() => ({})),
          fetch('/api/engine/news-bias').then(r => r.json()).catch(() => ({})),
        ]);

        const plan = engineRes?.plan;
        const usd = newsRes?.usd;
        const pairBias = (newsRes?.pairBiases || []).find((p: any) =>
          p.pair === primaryPair || p.pair === pairMap[cur]
        );

        // Compose human-readable summary from real data
        const parts: string[] = [];
        parts.push(`📊 Live Engine Analysis for ${event.title} (${cur})`);
        parts.push('');

        if (usd) {
          parts.push(`💵 USD Strength: ${usd.label} (${usd.score > 0 ? '+' : ''}${usd.score})`);
          parts.push('');
        }

        if (pairBias) {
          parts.push(`🎯 Engine Bias for ${pairBias.pair}: ${pairBias.bias} (${pairBias.confidence}% confidence)`);
          parts.push(`   ${pairBias.reason}`);
          parts.push('');
        }

        if (plan && plan.direction !== 'WAIT') {
          parts.push(`📈 Active Setup on ${plan.symbol} ${plan.timeframe}:`);
          parts.push(`   Signal: ${plan.direction} — ${plan.confidence}% confidence`);
          parts.push(`   Setup Type: ${plan.setupType}`);
          parts.push(`   Entry: ${plan.entry}`);
          parts.push(`   Stop Loss: ${plan.stopLoss}`);
          parts.push(`   TP1: ${plan.takeProfit1}`);
          parts.push(`   TP2: ${plan.takeProfit2}`);
          parts.push(`   R:R 1:${plan.riskReward.toFixed(1)}`);
          parts.push('');
          if (plan.reasons?.length) {
            parts.push('Why:');
            plan.reasons.slice(0, 3).forEach((r: string) => parts.push(`  ✓ ${r}`));
          }
        } else if (plan) {
          parts.push(`📈 Engine status on ${plan.symbol}: No active setup right now`);
          parts.push(`   Trend: ${plan.trend} · Session: ${plan.session} · RSI: ${plan.rsi?.toFixed(1) || 'N/A'}`);
          parts.push('');
        }

        parts.push('⚠️ This analysis is generated by the rule-based engine, not financial advice.');

        setAnalysisText(parts.join('\n'));
      } catch (err) {
        console.error('[MacroAnalysis]', err);
        setAnalysisText('Could not load live analysis. Please check your connection.');
      } finally {
        setLoading(false);
      }
    };

    fetchAnalysis();
  }, [isOpen, event]);

  if (!isOpen || !event) return null;

  const isHigh = event.impact === 'High';
  const isMedium = event.impact === 'Medium';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        id="macro-analysis-modal"
        className="w-full max-w-xl bg-white dark:bg-[#0a0c16] border border-[#e5e7eb] dark:border-[#1a1e30] rounded-3xl p-6 shadow-2xl text-[#111111] dark:text-white relative flex flex-col max-h-[90vh]"
      >
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-gray-100 dark:border-[#161828]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-[#faf9ff] dark:bg-[#141628] border border-purple-200 dark:border-[#272d4c] flex items-center justify-center text-[#5b3fe4] dark:text-purple-400">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-base font-bold text-gray-900 dark:text-white tracking-tight">{event.title}</span>
                <span className="text-sm">{event.countryFlag}</span>
              </div>
              <p className="text-[11px] text-gray-500 dark:text-gray-400 font-mono">ForexFactory AI Algorithmic Impact Prediction</p>
            </div>
          </div>
          <button
            id="close-macro-modal-btn"
            onClick={onClose}
            className="p-2 rounded-xl bg-gray-50 dark:bg-[#121422] text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-[#1a1e34] border border-gray-200 dark:border-[#1e2338] transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Compact Key Metric Chips */}
        <div className="grid grid-cols-4 gap-2 my-4">
          <div className="bg-gray-50 dark:bg-[#0f1120] p-2.5 rounded-xl border border-gray-200 dark:border-[#1c223a] text-center">
            <div className="text-[9px] uppercase tracking-wider text-gray-500 font-bold font-mono">IMPACT</div>
            <div className="pt-0.5">
              <span className={`text-[10px] font-bold uppercase font-mono px-2 py-0.5 rounded ${
                isHigh ? 'bg-rose-50 dark:bg-[#2b1216] text-rose-600 dark:text-[#ff4b58] border border-rose-200 dark:border-[#ff4b58]/30' : isMedium ? 'bg-amber-50 dark:bg-[#2b220e] text-amber-600 dark:text-[#f5a623] border border-amber-200 dark:border-[#f5a623]/30' : 'bg-gray-100 dark:bg-[#181a26] text-gray-600 dark:text-gray-400'
              }`}>
                {event.impact}
              </span>
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-[#0f1120] p-2.5 rounded-xl border border-gray-200 dark:border-[#1c223a] text-center">
            <div className="text-[9px] uppercase tracking-wider text-gray-500 font-bold font-mono">SCHEDULE</div>
            <div className="font-mono text-gray-800 dark:text-gray-200 text-xs font-semibold pt-1 truncate">
              {event.dateStr ? event.dateStr.split(',')[0] : (event.formattedDate || event.dayDate || 'Scheduled')}
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-[#0f1120] p-2.5 rounded-xl border border-gray-200 dark:border-[#1c223a] text-center">
            <div className="text-[9px] uppercase tracking-wider text-gray-500 font-bold font-mono">COUNTDOWN</div>
            <div className="font-mono text-emerald-600 dark:text-emerald-400 text-xs font-bold pt-1">
              {event.countdown}
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-[#0f1120] p-2.5 rounded-xl border border-gray-200 dark:border-[#1c223a] text-center">
            <div className="text-[9px] uppercase tracking-wider text-gray-500 font-bold font-mono">STATUS</div>
            <div className="font-mono text-[#5b3fe4] dark:text-purple-300 text-xs font-bold pt-1">
              AI READY
            </div>
          </div>
        </div>

        {/* Content Body with Small Easy-to-Scan Sections */}
        <div className="flex-1 overflow-y-auto pr-1 space-y-3.5 text-xs leading-relaxed custom-scrollbar">
          {loading ? (
            <div className="py-14 flex flex-col items-center justify-center gap-3 text-gray-400">
              <div className="w-8 h-8 border-2 border-purple-500 border-t-transparent rounded-full animate-spin" />
              <span className="text-xs font-medium">Running live engine analysis on {event.currency} pairs...</span>
            </div>
          ) : (
            <div className="space-y-3">
              {/* Live engine analysis text */}
              {analysisText ? (
                <div className="p-4 rounded-xl bg-gray-50 dark:bg-[#0a0c16] border border-gray-200 dark:border-[#16192c] text-gray-700 dark:text-gray-300 text-[12px] whitespace-pre-wrap leading-relaxed font-mono">
                  {analysisText}
                </div>
              ) : (
                <div className="p-6 rounded-xl bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-500/30 text-amber-800 dark:text-amber-300 text-xs text-center">
                  Live engine analysis temporarily unavailable. Try again in a moment.
                </div>
              )}

              {/* Disclaimer */}
              <div className="p-3 rounded-xl bg-gray-100 dark:bg-[#0a0c16] border border-gray-200 dark:border-[#16192c] text-[10px] text-gray-500 dark:text-gray-500 leading-relaxed">
                ⚠️ Analysis is generated by the rule-based engine from live candle data and ForexFactory news. Not financial advice. Always manage risk (1% per trade max).
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-gray-100 dark:border-[#161828] flex justify-end gap-2">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[#5b3fe4] hover:bg-[#4c32d4] text-white text-xs font-semibold rounded-xl transition-all shadow-sm active:scale-[0.98] cursor-pointer"
          >
            Acknowledge &amp; Close
          </button>
        </div>
      </div>
    </div>
  );
};
