import React, { useState, useEffect } from 'react';
import { X, FileText, Shield } from 'lucide-react';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultTab?: 'terms' | 'privacy';
}

export const TermsModal: React.FC<TermsModalProps> = ({
  isOpen,
  onClose,
  defaultTab = 'terms'
}) => {
  const [activeTab, setActiveTab] = useState<'terms' | 'privacy'>(defaultTab);

  useEffect(() => {
    if (isOpen) {
      setActiveTab(defaultTab);
    }
  }, [isOpen, defaultTab]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-150">
      <div
        id="terms-modal"
        className="w-full max-w-3xl bg-[#0b0c13] text-gray-200 rounded-3xl border border-[#1d202e] shadow-2xl relative flex flex-col max-h-[90vh] overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#1d202e] shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-[#14162a] border border-[#232744] flex items-center justify-center text-indigo-400">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-tight">
                Legal & Compliance
              </h3>
              <p className="text-[11px] text-gray-500">
                PipNex AI Platform — Legal Documentation
              </p>
            </div>
          </div>

          <button
            id="close-terms-modal-btn"
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl bg-[#12141f] border border-[#222638] text-gray-400 hover:text-white hover:border-[#2b3149] transition-all cursor-pointer"
            aria-label="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="px-6 pt-4 shrink-0">
          <div className="p-1 rounded-xl bg-[#12141f] border border-[#1e2232] flex items-center">
            <button
              type="button"
              onClick={() => setActiveTab('terms')}
              className={`flex-1 py-2 text-xs font-semibold rounded-lg transition-all cursor-pointer flex items-center justify-center gap-1.5 ${
                activeTab === 'terms'
                  ? 'bg-[#1e2234] text-white shadow-sm border border-[#2b3149]'
                  : 'text-gray-400 hover:text-gray-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Terms of Service</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('privacy')}
              className={`flex-1 py-2 text-xs font-semibold rounded-lg transition-all cursor-pointer flex items-center justify-center gap-1.5 ${
                activeTab === 'privacy'
                  ? 'bg-[#1e2234] text-white shadow-sm border border-[#2b3149]'
                  : 'text-gray-400 hover:text-gray-200'
              }`}
            >
              <Shield className="w-3.5 h-3.5" />
              <span>Privacy Policy</span>
            </button>
          </div>
        </div>

        {/* Content Body (Scrollable) */}
        <div className="flex-1 overflow-y-auto custom-scrollbar px-6 py-5 text-xs leading-relaxed text-gray-300 space-y-4">
          {activeTab === 'terms' ? (
            <>
              <section>
                <h4 className="text-sm font-bold text-white mb-2">1. Acceptance of Terms</h4>
                <p>
                  By accessing or using the PipNex AI platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the Service. These terms apply to all visitors, users, and others who access or use the Service.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">2. Description of Service</h4>
                <p>
                  PipNex AI provides AI-powered market analysis, trading signals, chart analytics, and educational tools for Forex, Commodities, Indices, and Cryptocurrency markets. The Service is strictly informational and educational. PipNex AI is <strong className="text-white">not a broker, dealer, or financial advisor</strong>, and we do not execute trades on your behalf.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">3. No Financial Advice</h4>
                <p>
                  All content, signals, and analysis generated by PipNex AI are for informational purposes only and should not be construed as financial, investment, or trading advice. You are solely responsible for your own trading decisions and for evaluating the risks associated with any trade. Past performance is not indicative of future results.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">4. Risk Disclosure</h4>
                <p>
                  Trading in financial markets involves substantial risk of loss and is not suitable for all investors. Leverage can work against you as well as for you. You should never trade with money you cannot afford to lose. PipNex AI does not guarantee profits, and any reference to performance metrics is not a promise of future returns.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">5. Account Responsibilities</h4>
                <p>
                  You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Provide accurate and complete registration information.</li>
                  <li>Keep your password secure and confidential.</li>
                  <li>Notify us immediately of any unauthorized use of your account.</li>
                  <li>Not share your account with any third party.</li>
                </ul>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">6. Subscriptions and Payments</h4>
                <p>
                  PipNex AI offers paid subscription plans. All payments are processed through third-party providers. By subscribing, you agree to the pricing, billing cycle, and renewal terms presented at checkout. Subscription plans can be modified or cancelled at any time, but refunds are subject to our refund policy.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">7. Acceptable Use</h4>
                <p>
                  You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, or impair the Service. Prohibited activities include but are not limited to:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Attempting to reverse-engineer, copy, or resell our algorithms.</li>
                  <li>Using automated tools to scrape data from the platform.</li>
                  <li>Uploading malicious code or attempting to breach our security.</li>
                  <li>Impersonating PipNex AI staff or other users.</li>
                </ul>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">8. Intellectual Property</h4>
                <p>
                  All content on the PipNex AI platform, including but not limited to algorithms, code, designs, text, and AI models, is the exclusive property of PipNex AI and is protected by copyright and other intellectual property laws.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">9. Limitation of Liability</h4>
                <p>
                  To the maximum extent permitted by law, PipNex AI and its developers, affiliates, and partners shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to trading losses, missed profits, or data loss.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">10. Modifications to Terms</h4>
                <p>
                  We reserve the right to modify these Terms of Service at any time. Changes will be posted on this page and will take effect immediately upon posting. Your continued use of the Service after changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">11. Contact</h4>
                <p>
                  For any questions regarding these Terms, please contact us at{' '}
                  <a href="mailto:Pipnexaicustomer@gmail.com" className="text-indigo-400 hover:underline">
                    Pipnexaicustomer@gmail.com
                  </a>
                  .
                </p>
              </section>

              <p className="text-[11px] text-gray-500 pt-4 border-t border-[#1d202e]">
                Last updated: September 2026
              </p>
            </>
          ) : (
            <>
              <section>
                <h4 className="text-sm font-bold text-white mb-2">1. Information We Collect</h4>
                <p>
                  We collect information you provide directly to us, including:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Account information: name, email, phone number, country.</li>
                  <li>Authentication data: securely hashed passwords.</li>
                  <li>Payment metadata: transaction references (we do not store full card numbers).</li>
                  <li>Usage data: pages visited, features used, session duration.</li>
                  <li>Device data: IP address, browser type, operating system.</li>
                </ul>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">2. How We Use Your Information</h4>
                <p>
                  Your information is used to:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Provide, maintain, and improve the Service.</li>
                  <li>Process transactions and send related confirmations.</li>
                  <li>Send verification codes, security alerts, and support messages.</li>
                  <li>Personalize your experience and content recommendations.</li>
                  <li>Detect, prevent, and address fraud or abuse.</li>
                </ul>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">3. Data Sharing</h4>
                <p>
                  We do not sell your personal information. We may share data with:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Payment processors (for completing transactions).</li>
                  <li>Cloud infrastructure providers (for hosting our services).</li>
                  <li>Legal authorities when required by law.</li>
                </ul>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">4. Data Security</h4>
                <p>
                  We use industry-standard security measures, including encrypted connections (HTTPS), hashed passwords, and access controls. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">5. Your Rights</h4>
                <p>
                  Depending on your jurisdiction, you may have the right to:
                </p>
                <ul className="list-disc pl-5 mt-1.5 space-y-1">
                  <li>Access the personal data we hold about you.</li>
                  <li>Request correction of inaccurate data.</li>
                  <li>Request deletion of your account and associated data.</li>
                  <li>Object to or restrict certain data processing.</li>
                  <li>Export your data in a portable format.</li>
                </ul>
                <p className="mt-2">
                  To exercise these rights, contact us at{' '}
                  <a href="mailto:Pipnexaicustomer@gmail.com" className="text-indigo-400 hover:underline">
                    Pipnexaicustomer@gmail.com
                  </a>
                  .
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">6. Cookies</h4>
                <p>
                  PipNex AI uses cookies and similar technologies to maintain your session, remember your preferences, and analyze usage. You can control cookies through your browser settings, though disabling them may affect platform functionality.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">7. Data Retention</h4>
                <p>
                  We retain your personal data for as long as your account is active or as needed to provide services. When you delete your account, we remove your personal data within 30 days, except where we are legally required to retain it.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">8. Third-Party Links</h4>
                <p>
                  The Service may contain links to third-party websites or services. We are not responsible for the privacy practices of those third parties. We encourage you to review their privacy policies.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">9. Changes to This Policy</h4>
                <p>
                  We may update this Privacy Policy from time to time. Changes will be posted on this page, and material changes will be communicated via email or in-app notification.
                </p>
              </section>

              <section>
                <h4 className="text-sm font-bold text-white mb-2">10. Contact</h4>
                <p>
                  For privacy-related questions, please contact us at{' '}
                  <a href="mailto:Pipnexaicustomer@gmail.com" className="text-indigo-400 hover:underline">
                    Pipnexaicustomer@gmail.com
                  </a>
                  .
                </p>
              </section>

              <p className="text-[11px] text-gray-500 pt-4 border-t border-[#1d202e]">
                Last updated: September 2026
              </p>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[#1d202e] flex items-center justify-end shrink-0">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl bg-gradient-to-b from-[#34294d] to-[#251c3a] hover:from-[#3e305e] hover:to-[#2d2247] border border-[#483b6b]/60 text-white text-xs font-bold transition-all cursor-pointer"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};
